-- Secure authentication schema for powered by nexora
-- Run this in Supabase SQL Editor before deploying the real backend login.

create table if not exists public.auth_users (
  id bigint generated by default as identity primary key,
  full_name text not null,
  username text not null unique,
  password_hash text not null,
  role text not null check (role in ('admin', 'manager', 'storekeeper', 'data_entry', 'readonly')),
  role_name text not null,
  status text not null default 'active' check (status in ('active', 'inactive', 'locked')),
  last_login_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists auth_users_username_idx on public.auth_users (username);
create index if not exists auth_users_status_idx on public.auth_users (status);

insert into public.auth_users (full_name, username, password_hash, role, role_name, status)
values
  ('مدير النظام', 'admin', 'pbkdf2_sha256$310000$oab-gT-NilIPqm2URArI8g$jCfaohkIof7xs7_QDu9ERyb_MTbEzGiaKbr-i_pqF7A', 'admin', 'مدير النظام', 'active'),
  ('أحمد المدير', 'warehouse.manager', 'pbkdf2_sha256$310000$1XU817YnyqDCojlKwz-ttw$DCVIHdQXM3Z5S0mqrbcLqGzOmPLMv-1g42aLZhHsOqA', 'manager', 'مدير المستودع', 'active'),
  ('أمين المستودع', 'storekeeper', 'pbkdf2_sha256$310000$a8frWB1KfkWNNuIeokWGIQ$aVd2TU8uSZ7JVRFemusai4u_8sBHIqUSWHTuGuZ6FIg', 'storekeeper', 'أمين المستودع', 'active'),
  ('موظف إدخال', 'data.entry', 'pbkdf2_sha256$310000$VVrwrYOJTeNKAqsEUUB7hg$juIRZZDYiOqL_J4DRKRG1Jwmi1h7EZsSgFl1QxE7t4c', 'data_entry', 'موظف إدخال', 'active'),
  ('مستخدم قراءة', 'readonly', 'pbkdf2_sha256$310000$Zm4zAzfdX468wXMTeRZ4dw$iv6t9qfRqMseVYp326ZEvbZ43l9RGdrjpRxZ8tErvuk', 'readonly', 'قراءة فقط', 'active')
on conflict (username) do nothing;

-- Initial login users:
-- admin / admin123
-- warehouse.manager / manager123
-- storekeeper / store123
-- data.entry / data123
-- readonly / read123
-- Change these passwords from the Users page after first login.
